### ISSUE TITLE
Glog: "Undefined variable: b:git_dir" with startify

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-fugitive#1132]
Using `:Glog` on a [vim-startify](https://github.com/mhinz/vim-startify) buffer fails:

```
Error detected while processing function <SNR>45_Log:                              
line   29:
E121: Undefined variable: b:git_dir
E116: Invalid arguments for function s:shellesc
E116: Invalid arguments for function escape
E15: Invalid expression: escape(s:UserCommand() . ' --no-pager log --no-color ' . s:shellesc(
'--pretty=format:fugitive://'.b:git_dir.'//%H'.path.'::'.g:fugitive_summary_format), '%#')
```

This is due to the `cd` (for the same dir, i.e. it could be skipped) triggers `DirChanged`, and vim-startify runs `Startify` then, which includes `enew`.

It is unfortunate that Vim triggers `DirChanged` in the first place already for `:exe 'cd '.getcwd()`.

I've found that vim-fugitive could also handle Neovim's tab-local directories, and that a helper like the following might be good to use:
```vim
function! s:temp_cd(dir) abort
  let dir = getcwd()
  if a:dir ==# dir
    return ''
  endif
  let cd = haslocaldir() ? 'lcd' : (exists(':tcd') == 2 && haslocaldir(-1, 0)) ? 'tcd' : 'cd'
  execute s:fnameescape(a:dir)
  return cd.' '.a:dir
endfunction
```

/cc @mhinz

**Comment by tpope** [comment]
Sounds like this is solved twice over?

**Comment by blueyed** [comment]
Yes, thanks.

Neovim's `:tcd` is still not supported though.. ;)

**Comment by tpope** [comment]
Adding `:tcd` without a `haslocaldir()` solution (there's not a solution is there?) is one of the most inarguable examples of bad project management in Neovim.

**Comment by mhinz** [comment]
`haslocaldir()` _is_ the solution. :)

```
haslocaldir([{winnr}[, {tabnr}]])			*haslocaldir()*
		The result is a Number, which is 1 when the tabpage or window
		has set a local path via |:tcd| or |:lcd|, otherwise 0.

		Tabs and windows are identified by their respective numbers,
		0 means current tab or window. Missing argument implies 0.
		Thus the following are equivalent: >
			haslocaldir()
			haslocaldir(0)
			haslocaldir(0, 0)
<		With {winnr} use that window in the current tabpage.
		With {winnr} and {tabnr} use the window in that tabpage.
		{winnr} can be the window number or the |window-ID|.
		If {winnr} is -1 it is ignored, only the tab is resolved.
```

So, basically..

```vim
  let chdir = haslocaldir()
        \ ? 'lcd'
        \ : (exists(':tcd') && haslocaldir(-1, 0)) ? 'tcd' : 'cd'
```

**Comment by tpope** [comment]
Eesh, at least it's possible I guess.
