### ISSUE TITLE
`:G` does not show anything

### ISSUE THREAD

**Issue by nguyentritai2906** [tpope/vim-fugitive#1841]
I have a problem similar to #1818 where `:G` doesn't show any untrack/unstage/unpush files and I'm sure that's it's on my side but I can't figure out what is wrong. Please excuse my ignorance and inexperience. I hope you can help me out

I manage my dotfiles using a bare repo following Atlassian [tutorial](https://www.atlassian.com/git/tutorials/dotfiles) and use an alias `GIT_DIR=$HOME/.cfg GIT_WORK_TREE=$HOME vim` to edit them but for an unknown reason (to me)
1. `:G` command doesn't show any section but `git --git-dir=$HOME/.cfg/ --work-tree=$HOME status` still show as normal
2. When I do `:Gw` on a file it just disappear. It seems like vim just open a new empty buffer. I tried execute `:file` and it return `"[No Name]" --No lines in buffer--`
3. `:echo FugitiveStatusline()` return `[Git(master)]` but lualine doesn't show anything

Step to reproduce:
```
~/tmp ❯ git clone --bare https://github.com/tpope/vim-fugitive.git
Cloning into bare repository 'vim-fugitive.git'...
remote: Enumerating objects: 8083, done.
remote: Counting objects: 100% (1324/1324), done.
remote: Compressing objects: 100% (400/400), done.
remote: Total 8083 (delta 654), reused 1175 (delta 583), pack-reused 6759
Receiving objects: 100% (8083/8083), 2.48 MiB | 4.91 MiB/s, done.
Resolving deltas: 100% (3748/3748), done.
~/tmp took 3s ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp checkout master
Already on 'master'
~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp fetch --all
Fetching origin
From https://github.com/tpope/vim-fugitive
 * [new branch]      blame_color     -> origin/blame_color
 * [new branch]      blame_message   -> origin/blame_message
 * [new branch]      buffer_path     -> origin/buffer_path
 * [new branch]      copied          -> origin/copied
 * [new branch]      difftool        -> origin/difftool
 * [new branch]      http_github_fi  -> origin/http_github_fi
 * [new branch]      master          -> origin/master
 * [new branch]      nested/test     -> origin/nested/test
 * [new branch]      parallel-status -> origin/parallel-status
 * [new branch]      symlink         -> origin/symlink
 * [new branch]      worktree        -> origin/worktree
 * ~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp branch master -u origin/master
Branch 'master' set up to track remote branch 'master' from 'origin'.
~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp branch -a
  blame_color
  blame_message
  buffer_path
  copied
  difftool
  http_github_fi
* master
  nested/test
  parallel-status
  symlink
  worktree
  remotes/origin/blame_color
  remotes/origin/blame_message
  remotes/origin/buffer_path
  remotes/origin/copied
  remotes/origin/difftool
  remotes/origin/http_github_fi
  remotes/origin/master
  remotes/origin/nested/test
  remotes/origin/parallel-status
  remotes/origin/symlink
  remotes/origin/worktree
(END)
~/tmp took 8s ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp branch -vv
  blame_color     70eba58 Timestamp WIP
  blame_message   62c50ff Handle .git in file system root
  buffer_path     2723a11 Return '' from buffer.path() if outside work tree
  copied          ea7b1ab Support "copied:" lines in :Gstatus
  difftool        ef87434 Provide :Git difftool and :Git mergetool
  http_github_fi  ff32149 Attempt to allow :Gbrowse on HTTP GitHub FI
* master          27abc3f [origin/master] Respect 'splitright' instead of 'splitbelow' for :vertical
  nested/test     f61beed Add packed-ref handling
  parallel-status 195edd1 Run status buffer Git commands in parallel
  symlink         acd9c3e Force resolution of symlinked buffers
  worktree        16c2b7a Support worktrees
(END)
~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp config --local -l
core.repositoryformatversion=0
core.filemode=true
core.bare=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=https://github.com/tpope/vim-fugitive.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
(END)
~/tmp took 9s ❯ GIT_DIR=$HOME/tmp/vim-fugitive.git GIT_WORK_TREE=$HOME/tmp vim README.markdown
```

Modify the file and `:w` then execute `:G`

Expected: 
```
Head: master
Push: origin/master
Help: g?

Unstaged (1)
M README.markdown
```

Output:
```
Head: master
Push: origin/master
Help: g?
```

```
~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   README.markdown

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        vim-fugitive.git/

no changes added to commit (use "git add" and/or "git commit -a")
~/tmp ❯ git --git-dir=$HOME/tmp/vim-fugitive.git --work-tree=$HOME/tmp diff origin/master
diff --git a/README.markdown b/README.markdown
index f572ce2..62e1368 100644
--- a/README.markdown
+++ b/README.markdown
@@ -2,6 +2,8 @@

 Fugitive is the premier Vim plugin for Git.  Or maybe it's the premier Git
 plugin for Vim?  Either way, it's "so awesome, it should be illegal".  That's
+
+
 why it's called Fugitive.

 The crown jewel of Fugitive is `:Git` (or just `:G`), which calls any
(END)
```

Attempt to write and commit with `:Gw` open an empty buffer. Execute `:file` return `"[No Name]" --No lines in buffer--`

Thank you for your time

**Comment by tpope** [comment]
Fugitive is designed to work with multiple repositories in a single Vim instance. All setting `GIT_DIR` and `GIT_WORK_TREE` does is break things. You're not the first person to try this, so I've pushed a change to work around the damage. `:Git` will now behave exactly like `git` with no arguments, that is to say, it will correctly fail to work.


See #1796 for further discussion and a possible alternative solution.

**Comment by nguyentritai2906** [comment]
Hello, I've read through the discussion but I'm still not sure how to use `FugitiveDetect()`. I've tried `:call FugitiveDetect('path/to/repo/.foobar')` and `:Git` shows the status as expected but it doesn't show any sections. `:Gw` now return `fugitive: fatal: this operation must be run in a work tree`

**Comment by tpope** [comment]
You need to pass the path to the Git repo. Looks like `expand('~/.cfg')` in this case.

**Comment by tpope** [comment]
And you probably need to set `core.worktree`.

**Comment by nguyentritai2906** [comment]
I needed to set `core.worktree` and unset `core.bare`. Thank you for your time. I greatly appreciate it
