### ISSUE TITLE
After upgrading macOS Monterey 12.3, I got some error when I run vi <filename> on iterm2

### ISSUE THREAD

**Issue by lnto3408** [tpope/vim-fugitive#1959]
Hi, currently I'm facing the following error after upgrading macOS Monterey 12.3:

```
Error detected while processing /Users/test/.vim/bundle/vim-fugitive/plugin/fugitive.vim:
line  472: E1208: -complete used without allowing argumentsline  473: E1208: -complete used without allowing argumentsline  477: E1208: -complete used without allowing argumentsline  480: E1208: -complete used without allowing argumentsError detected while processing /Users/test/.vim/bundle/coc.nvim/plugin/coc.vim:
line  446: E1208: -complete used without allowing argumentsPress ENTER or type command to continue
```

`472: exe 'command! -bar -bang -nargs=0 -complete=customlist,fugitive#CompleteObject GRemove exe fugitive#RemoveCommand(<line1>, <count>, +"<range>", <bang>0, "<mods>", <q-args>, [<f-args>])'
`

Is anyone facing the same issue?

**Comment by lnto3408** [comment]
I've fixed this issue after updating code. thanks for your attention.

**Comment by malash** [comment]
Hello @lnto3408 , would you mind keep the issue opening until the bug is fixed so users can track the issue ? Thanks.

**Comment by tpope** [comment]
> I've fixed this issue after updating

This. Update. This "bug" (actually a Vim regression) was fixed months ago.

**Comment by okcompute** [comment]
Hi @tpope,

> This "bug" (actually a Vim regression) was fixed months ago.

I now get this error message as well since I installed macOS 12.3. My Vim version is 8.2.4550 (released 7 days ago). Should I report this problem as not fully resolved on the Vim issue tracker?

Thanks!

**Comment by tpope** [comment]
Vim's regression is wontfix. Fugitive has a workaround, included in the latest stable release.

**Comment by okcompute** [comment]
> Vim's regression is wontfix. Fugitive has a workaround, included in the latest stable release.

Got it! I confirm that updating vim-fugitive to the latest fixes the issue. Thank you for your quick response and this plugin. 🙏
