### ISSUE TITLE
:Gblame gives "fugitive: file or blob required" seemingly randomly

### ISSUE THREAD

**Issue by xiongchiamiov** [tpope/vim-fugitive#451]
Sometimes when I use `:Gblame`, I get the "file or blob required" error; sometimes I don't.  These are all with the same vim configuration, on the same machine, in the same codebase even - I haven't been able to determine any common factors.

The mysterious `set bufhidden=delete` command specified in #379 does not help.

**Comment by mctully** [comment]
This happens to me occasionally too. In my case, I'm on Windows, and when I check b:git_dir compared to exapnd('%:p') the most obvious difference is the case of the drive letter. b:git_dir had a lower case 'e:/' as the drive letter, and expand('%:p') had upper case.

I re-launched Vim from a path which I'd cd-ed into using an upper case E:/ and then :Gblame worked.

Perhaps on Windows it could cater for a difference in the drive letter somehow?

**Comment by tpope** [comment]
That issue in particular should have been solved (rather crudely) by f8bf95b9ff838ede04ab02487524849fb03a2576.

**Comment by tpope** [comment]
Thinking about it, it's now clear that was only half the solution.

**Comment by mctully** [comment]
Sorry - worst bug report ever - I forgot to say which version I was running :)

I'm on 0fbbe0b3a44b and so I already have tested with f8bf95b and see that the issue still occurs.

**Comment by tpope** [comment]
ca727b0 fixes it though, right?

**Comment by mctully** [comment]
Ah I hadn't tried ca727b0, trying that now, I get a new error both on loading a file and when invoking :Gblame

    Error detected while processing function <SNR>23_Blame..<SNR>23_buffer_path..<SNR>23_cpath:
    line    1:
    E113: Unknown option: fileignorecase
    E15: Invalid expression: &fileignorecase       

Tbh, I had a bit of trouble re-creating it this morning using master (0fbbe0b3a) even before grabbing ca727b0, for some reason both expand("%:p") and b:git_dir had matching upper case letters. In the end I forced the issue from within Vim by using :e e:\path\to\my\file , this forced b:git_dir to have a lower case drive letter whilst expand("%:p") kept the upper case one. Doing :Gblame in that state caused the 'file or blob required' error.

I then closed Vi and took ca727b0, but was unable to test due to the "Invalid expression" error above. I'm on VIm for Windows 7.3.46

**Comment by tpope** [comment]
You'll need to update to a version with `'fileignorecase'` (7.4 should do it).

**Comment by mctully** [comment]
Ah - right. I've upgraded to 7.4 and with ca727b0 the problem is fixed!

I got a solid repro and I was able to upgrade fugitive and show the problem went away. I then rolled fugitive back and proved the problem came back.

Fix looks good to me - thanks very much for your help!

**Comment by ciupicri** [comment]
If I move the `.git` directory somewhere else and put a symlink to it, I get the same error. Is this case too "funky"?

**Comment by tpope** [comment]
A simple symlink is (apparently) unsupported but you can achieve the desired effect of keeping your Git dir elsewhere with Git worktrees.

**Comment by aschrab** [comment]
I think the `--separate-git-dir=` option to `git init` or `git clone` would be a better substitute for this than worktrees.

**Comment by tpope** [comment]
Yeah that must have been what I was thinking of.

**Comment by jesse-c** [comment]
I've just started seeing this a few days ago (not aware of anything noteworthy changing on my machine, especially with my vim config). Anyway extra debug information I should look at to see what's happening?

I'm using Neovim 0.3.4 on macOS 10.14.3 (18D109).

**Comment by tpope** [comment]
This should only happen when the current file's path doesn't appear to be inside `FugitiveWorkTree()`. This can happen if you rename the file or do something sufficiently weird with symlinks.

**Comment by jesse-c** [comment]
`:echo FugitiveWorkTree()` is returning `/Users/xxxx/.local/share/nvim/plugged/vim-fugitive`. I tried with only fugitive in my vimrc [1] and it still has the same issue. So I've got some weird change in my local environment that's messing it up. Any suggestions on where I should look?

[1]
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()
```

**Comment by tpope** [comment]
What does `:echo expand('%:p')` return in that same buffer?

**Comment by jesse-c** [comment]
`:echo FugitiveWorkTree()` is now returning (restarted my computer) the correct path, and `:echo expand('%:p')` is returning the expected path to the open file, though I'm still getting the error.

Of note, these are Git workspaces I'm in. It seems to consistently work in non-workspaces. It's also working in the original git dir (that the others are workspaces of).

**Comment by tpope** [comment]
Does workspace mean worktree? I just confirmed it's working for me with a simple worktree setup.

I think I need to see your actual paths.

**Comment by jesse-c** [comment]
Sorry, I meant worktree! I had no issues with it for over a year, so it's definitely an issue on my end. It's working in other example worktree setups locally for me too. 

It's just unfortunately working in our monorepo where I spend 99% of my time haha. 

Dumb question, but which paths exactly would be helpful in debugging?

**Comment by tpope** [comment]
`FugitiveWorkTree()` and `expand('%:p')` for a file you can't blame.
