### ISSUE TITLE
wrong Gdiff target for .git repo2 inside .git repo1

### ISSUE THREAD

**Issue by step-** [tpope/vim-fugitive#887]
With this folder structure
```
.
├── .git/
├── install/
│   ├── .git/
│   ├── installer.sh
├── README.md
```
where `./install/.git` **isn't** a git sub-module of `./.git`,
and this git status
```
# git status

On branch master
Changes not staged for commit:

	modified:   README.md
	modified:   install/installer.sh

# gvim
```
If I run gvim in '.' with no arguments (no open files) and execute `:Gstatus` I get the same status readout (OK).
Then I move the cursor to the install/installer.sh line and press 'D'. I get a diff view of 
`./install/.git//0/install.sh` and `./install/installer.sh` (incorrect)
instead of
`./.git//0/install.sh`         and `./install/installer.sh`
as `:Gstatus` implies.

Linux, git version 2.7.0, vim fugitive commit 87c1bda, vim 8.0.134

Thanks

**Comment by MadeOfMagicAndWires** [comment]
May I ask why it *isn't* it a submodule, or a  subtree? This is a bug to be sure, but at the same time this is unintended use of git so it's not entirely unexpected.

**Comment by step-** [comment]
You certainly may ask. As several other projects in the tree, the sub-tree git repo is planned for conversion to a sub-module, but the change is taking longer than expected, and someone else owns it. Meanwhile, I have to keep maintaining the code.

**Comment by tpope** [comment]
Wasn't there a CVE for nested `.git` directories that was fixed in Git by disallowing them? Is this moot?

If it's not moot, there's a very good chance the new `:Gstatus` fixed it. Report back if not.

**Comment by step-** [comment]
I tested it and I don't think it's fixed.  With the steps given above, initially fugitive seems to pick up ./.git as the repo, so `Glog` and `G log` consistently report ./.git's log history. Likewise, `Gstatus` is about ./.git. However, after the `Gstatus`, fugitive picks ./installer/.git as the repo, so performing another `Glog` shows that repo's log and not ./.git's anymore.  It isn't clear to me where a Gcommit would go at this stage. Also, if I close the Gstatus split and issue another `Gstatus`, this time fugitive shows ./installer/.git's git status and not ./.git's as before.

I should mention that file `installer/installer.sh` is committed in both ./installer/.git and ./.git - of course as different objects because the two repos are unrelated; and `./.gitignore` doesn't exclude `./installer/`.

**Comment by step-** [comment]
I just tested master and things go differently. `Gstatus` appends this error message to the quickfix window:
```
|| /bin/sh: git -C /path/to/install --no-pager -c 'diff.context=0' -c 'diff.noprefix=false' log --no-color --no-ext-diff '--pretty=format:fugitive %h	%H %s': No such file or directory
```
This seems to be a new quoting problem unrelated to this issue. There's also this message:
```
Use :0Glog or :0Gclog for old behaviour of targeting current file
```
When I try `:0Glog` fugitive appends this error message to the quickfix window:
```
|| /bin/sh: $'git --no-pager -c \'diff.context=0\' -c \'diff.noprefix=false\' log --no-color --no-ext-diff \'--pretty=format:fugitive %h\t%H %s\'': command not found
```
Back to the current issue, with master when I run `:Gstatus` and `:G status` I get the same output, which is ./installer/.git's status (even though the current directory holds ./.git). You can guess it, when I run `:! git status` I get a different output (./.git's status). So, I think it works better now, in the sense that fugitive's notion of which is the current repo seems to have stabilized to a single repo (the one closest above the file path).

Now I wonder how can I manage the same file path as two objects of the nested repositories. Is this possible? I'm not concerned about the lower (contained) repo, because I can always cd to its folder before running vim. But what about the installer/installer.sh file stored in ./.git's repo - how can I address it from within fugitive when the current folder is ./.git?  Thank you.

**Comment by tpope** [comment]
Extremely strange `:Glog` errors. What does `:verbose set shell? shellcmdflag?` report?

**Comment by tpope** [comment]
Oh nevermind, I broke `:Glog` last night. Latest should fix it.

**Comment by tpope** [comment]
Okay, real question. What does `:echo [@%, b:git_dir]` report in that first `:Gstatus` window?

**Comment by step-** [comment]
Latest master fixed `:Gclog`, which reports for `./install/.git`.
> What does `:echo [@%, b:git_dir]` report in that first :Gstatus window?

    ['/path/to/cwd/install/.git/index', '/path/to/cwd/install/.git']

**Comment by tpope** [comment]
Okay, your first example says you're expecting `./.git//0/install.sh` but the name of the file in the status output is `installer.sh`. You butchered something and I can't tell what.

It would help if you gave me an example repo to test on with exact usage instructions demonstrating the problem.

**Comment by step-** [comment]
OK, here's two initial nested repos, which I'll refer to as top and bottom. Each repo holds an initial commit to the same empty file. (I also amended the commit messages for clarity). Unpack the attachment in /tmp and try to reproduce this console output.
[repo-in-repo.tgz.zip](https://github.com/tpope/vim-fugitive/files/3512067/repo-in-repo.tgz.zip)
```
# cd /tmp/repo-in-repo/install/
# date >> install.sh 
# git add install.sh && git commit -m "change 1 under"
[master 0cea8db] change 1 under
 1 file changed, 1 insertion(+)
/tmp/repo-in-repo
# date >> install.sh 
# cd ..; pwd
/tmp/repo-in-repo
# git diff |cat
diff --git a/install/install.sh b/install/install.sh
index e69de29..7db0ed2 100644
--- a/install/install.sh
+++ b/install/install.sh
@@ -0,0 +1,2 @@
+Sat Aug 17 14:52:15 CEST 2019
+Sat Aug 17 14:52:50 CEST 2019
# (cd install/; git diff |cat)
diff --git a/install.sh b/install.sh
index 0c7b0aa..7db0ed2 100644
--- a/install.sh
+++ b/install.sh
@@ -1 +1,2 @@
 Sat Aug 17 14:52:15 CEST 2019
+Sat Aug 17 14:59:50 CEST 2019
# 
gvim
```
Console output shows that from top's git perspective the working install/install.sh has two more lines wrt to the initial commit. From bottom's perspective the working install.sh - same file as above - has one more line wrt to the "change 1 under" commit.  Nothing surprising here.

Now you're in gvim, `:pwd` to ensure you started gvim in /tmp/repo-in-repo (top), as it should be. Do a `:Gstatus` and you'll see 1 unstaged: `M install/install.sh`. So far so good and nothing's broken.

Now move  the vim cursor to that line and press dd to get a gitdiff split. Something's odd; the split is seen from bottom's point of view not top's even though top's is the current directory. I would expect for fugitive to target the repo in the current directory, since it already holds an objected for the changed file.  This is where it gets confusing. Fugitive's Gstatus shows a path relative to top, but `dd` shows a diff relative to bottom.  Which repo will take the Gcommit?   If it's the bottom repo, how can I manage the object in the top repo from fugitive, if I can?

I hope the issue is more clear now.  Thank you.

**Comment by tpope** [comment]
The innermost repository always wins. Fugitive does not care about the working directory; it looks at the current filename and starts walking upwards to the first `.git` directory. The `dd` map opens the file and then calls `:Gdiffsplit!`, so the fact it started from a different `:Gstatus` buffer doesn't affect the end result.

This very specific problem could be fixed by having the `dd` map load the right index buffer, but all the commands in the work tree buffer like `:Gcommit` would still target the inner repository, so I think this would be more confusing than helpful.

The only good news I can offer is that if you use the new inline diffing on `=`, you can stage changes without leaving the status window, sidestepping the problem.

**Comment by step-** [comment]
That is useful, thank you. I just noticed that if I _first_ edit install/install.sh _then_ do `:Gstatus` everything is consistent and refers to the bottom repo. So it seems that the inconsistency arises from not having loaded any buffers, as in starting gvim without arguments.

**Comment by tpope** [comment]
There's a begrudging compromise where starting Vim with no arguments uses `getcwd()` for that initial unnamed buffer.
